# -*- coding: utf-8 -*-

if __name__ == '__main__':
    str1 = 'HHHYA NIHAOYA KANDAONIDE KANXINWOXINLIGANJUE BIJIDOUGAOXING BUYOUZIZHUDE SHAXIAOLEHENJIU ZUIBAHEBULONGLE NAZHONG' \
           'TONGSHIDOUYIWEI WOSHALE GANJUEBIJIHAIYAOKAIXINNE WOZHIDOA ZHEZHONGZHUANG TAIXIA HENNAN JIZHONGZHUYI LI GONGZUO' \
           'DANSHI NE WOBINGMEIYOU JUEDE '