#!/bin/bash

[ -z $1 ] && echo input hostname && exit

hostname=$1
ip=`ifconfig eth0|grep 'inet addr'|awk '{print $2}'|awk -F ":" '{print $2}'`

hostname $hostname
sed -i "s/HOSTNAME=.*/HOSTNAME=$hostname/" /etc/sysconfig/network

#修改hosts的主机名
#sed -i "s/\(127.0.0.1 *\).*\( localhost.localdomain.*\)/\1$hostname\2/" /etc/hosts
#sed -i "1,127.0.0.1 $hostname" >> /etc/hosts
#sed -i "2,$ip $hostname" >> /etc/hosts
cat > /etc/hosts << ENDF
127.0.0.1 localhost
127.0.0.1 $hostname
$ip $hostname
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
ENDF


#
#sed -i "1s/localhost/$hostname/" /etc/hosts
#
#sed -i '41,50s/^net.ipv4.*//' /etc/sysctl.conf
#
cat > /etc/resolv.conf << ENDF
#options timeout:1 attempts:1 rotate
#; generated by /sbin/dhclient-script
nameserver 10.1.20.18
nameserver 10.1.20.86
nameserver 10.0.146.215 
nameserver 100.100.2.136
nameserver 100.100.2.138
ENDF

